### PR TITLE
feature(grid): ability to dynamically add or change Column Headers

### PR DESCRIPTION
**Pull request by ghiscoding**
- We can dynamically add or change column definitions, see Example12 for a demo
- reference to issue #57

### CODE REVIEW

**Comment by ghiscoding** [comment]
@jmzagorski 
Looked at the open issues and saw that the issue #42 to change default binding on `dataset` might also expand to current PR. If so, can you make the changes or tell me what to change. Thanks

**Comment by jmzagorski** [comment]
with #42 all you have to do is change this:

```diff
-@bindable({ defaultBindingMode: bindingMode.twoWay }) dataset: any[];
+@bindable dataset: any[];
```

The reason: `twoWay` implies that `AureliaSlickGridCustomElement` will or can update the `dataset` and the changes will be propagated back to the view model (hence the name two-way). I believe, by default, custom elements have a binding of `oneWay` (from the view model to the custom element).

I do not think we will ever be need to mutate the dataset...right?

**Comment by jmzagorski** [comment]
will now close #42

**Comment by ghiscoding** [comment]
> I do not think we will ever be need to mutate the dataset...right?

but technically, a user could come and change the JSON dataset, I actually also do that with the OData backend service I think. We also need to support data insert, in that case we push to the dataset/dataView. Unless I misunderstood, don't we still need a two way binding for that to work?

**Comment by jmzagorski** [comment]
It is fine if the user/viewmodel changes the dataset since those changes will always flow into the AureliaSlickgridCustomElement, but if AureliaSlickGridCustomElement class changes the dataset  (ie changes the instance to another variable) then that change won't update the viewmodel dataset. As you found out in the examples everything should still work as expected

Nothing more in the pipeline from me right now.

**Comment by ghiscoding** [comment]
ok good, so you said you can close #42 since it was incorporated in this PR ?

**Comment by jmzagorski** [comment]
Yes #42 can be closed after this is merged

**Pull request merged**
