### PR TITLE
feat(ci): replace CircleCI by GitHub Actions

### PR DESCRIPTION
**Pull request by ghiscoding**

### CODE REVIEW

**Comment by zewa666** [comment]
That looks pretty ... slick ;)

The only thing I'm unsure is the npm Install together with using yarn. Isnt that conflicting? Also with npm you'd go with `npm ci` to speed up installs and make them use fixed versions. I dont use yarn so is there an equivalent?

**Comment by zewa666** [comment]
Ahh ok so thats what bahmutov/npm-install@v1 does under the hood. Cool lgtm

**Comment by ghiscoding** [comment]
ahh right I used Yarn in Slickgrid-Universal because of Lerna with Yarn Workspaces but I guess I don't need it here though. I could remove it. The `bahmutov/npm-install@v1` is what I found to work with Cypress being inside another sub-folder (not in the root) as it was describe in Cypress Github Action [here](https://github.com/cypress-io/github-action#subfolders)

**Comment by zewa666** [comment]
Yep just read that as well. Perhaps wait for the switch until you switch to npm7 workspaces and make sure to check in the package-lock.json as well. bahmutov/npm-install@v1 will handle that as well

**Comment by zewa666** [comment]
I also thought since aurelia-slickgrid and universal is Open source you should be able to request the [Cypress OSS](https://www.cypress.io/oss-plan/) plan to make use of the Dashboard as indicated by @bahmutov s action you can directly push artifacts there

**Comment by ghiscoding** [comment]
hmm I tried adding the recording key the other day and it seems that I reached their limit quite fast, but now the link you sent seems to show no recording limit for Open Source project, perhaps I didn't do it correctly or they changed it again.

**Comment by zewa666** [comment]
Ah and while on it, perhaps running the lint task would be a good idea as well

**Comment by ghiscoding** [comment]
the lint is already on the build npm script as a prebuild ;)

**Comment by ghiscoding** [comment]
guess I'm done... anything else before I merge? :P

**Comment by zewa666** [comment]
Lgtm, :shipit:

**Pull request merged**
