### PR TITLE
feat(grid): dispatch all grid/dataview events

### PR DESCRIPTION
**Pull request by jmzagorski**
Hopefully you will find this pull request helpful and aligned with your vision for this library. 

I noticed in your `GridEventService` you were firing the `onCellChange` and `onClick` event directly on the column definition if it exists, which is very helpful. However, sometimes I only care about this event occurring on the grid and not specific to a column. For example, `onCellChange` can fire on any of my columns and I want to handle it the same for all columns by sending the row to my PUT api. Therefore, it would be nice if I could subscribe to an event in the view using aurelia's delegate binding. This pull requests adds support for that by adding `dispatchEvent` for every slick grid/dataview event. I could not find a piece of code that was doing this already in your library.

You'll notice in your `AureliaSlickGridCustomElement`, I subscribe to all events by iterating over the properties that start with `on` and dispatching a DOM event. I chose to use `sg` as the event prefix to make it unique to "SlickGrid", but this can be changed. Also, I changed the event name to kebab case so it is more in line with how events are conventionally written in a view. 

I did not test all the events, just a few from the API page and they worked, but I did have a problem with onDblClick not firing. If you want me to test all of them I can do that.

As a side note I was having line ending issues on the commit after building. I develop on windows 10 vim, so I must have had a different settings. I added a local `.gitattributes` file with `* text=auto` and it fixed everything except the \dist\styles\css\* files (i just left those out). Not sure if it is my settings in particular or if it would be good to have the `.gitattributes` in another commit.

Thanks.

### CODE REVIEW

**Comment by ghiscoding** [comment]
Thanks a lot for the PR, I'll seriously look into it. You bring some interesting things with it. 

First a little bit of history and why the code is how it is.
I have, and maintain, another repo for [Angular-Slickgrid](https://github.com/ghiscoding/Angular-Slickgrid) because that is what my work chose to go with (I pushed for Aurelia but I didn't have the final word) and that repo is built and is advancing during working hours, they let me make it open source in hope of the community support and contributions (just like you did, thanks). Since I personally prefer Aurelia, I created Aurelia-Slickgrid as well but you can imagine that most of these features are actually coming in Angular first. Since it's mostly TypeScript I manage to get most of it copied over from one repo to the other without too much hassle, I would say about 90% is copied from 1 to the other without recoding while about 10% are things related to framework specific. 

Second why choose SlickGrid?
I used SlickGrid a few years ago and I loved it for it's customization and I'm happy to be back with it. However SlickGrid is a jQuery library and what my code does so far is basically wrapping the core and features so that it's usable in the chosen framework, A great example of that are SlickGrid Formatters, they are plain and simply html+javascript and not framework Component/View, but hey they works without much efforts, so why not... oh and they are totally movable from a framework to another without even a byte of code change since it's pure html/js and TypeScript.  

Alright enough history, but I wanted to mention that history so that you understand where I'm going with this. A lot of the code is in TypeScript and I try to make everything work between both framework without too much recoding. 

I didn't want to expose too much events because SlickGrid already exposes a lot of them and didn't want to recode and re-expose the same events over and over since I can simply pass the SlickGrid object, I talk about this in my [Wiki - onEvents](https://github.com/ghiscoding/aurelia-slickgrid/wiki/Grid-&-DataView-Events) which have links to all [SlickGrid Events](https://github.com/6pac/SlickGrid/wiki/Grid-Events). When you say this:
> You'll notice in your AureliaSlickGridCustomElement, I subscribe to all events by iterating over the properties that start with on and dispatching a DOM event.

Did you mean that you manage to expose all the SlickGrid events and making them Aurelia events? If that is the case, **it's totally awesome!** 

Also please note that I'm not an Aurelia expert at all, I only use Aurelia during spare time which isn't all that much and I didn't know about `dispatchEvent` (if you have good article please send over), I was only using the `Event Aggregator`, but it looks like `dispatchEvent` is more on the Element side of it, I have to read about that. 

Before I can accept the PR, would it be possible create (or modify) a Wiki page to demonstrate what your PR will help with. I try to provide as much documentation as possible through my [Wiki](https://github.com/ghiscoding/aurelia-slickgrid/wiki) section. I even refer to these doc when I forget how to use my own code lol.

**Comment by ghiscoding** [comment]
Side note 1
I also develop on Win10 but with Visual Studio Code, the new line ending comes from the editor I believe. The other good thing about VSCode is that I have a bunch of [Tasks](https://code.visualstudio.com/docs/editor/tasks) that I can run (start Dev build, start Doc build, Build lib, ...), you can see them [here](https://github.com/ghiscoding/aurelia-slickgrid/blob/master/.vscode/tasks.json). The Build Lib task is made as an NPM script which you obviously found and the bulk of these scripts comes from an Aurelia library, which I forgot which one it was, I kept most of the TSLint and TSconfig defaults, they are quite aggressive in some cases though.

Side note 2
I usually work on Aurelia code on Saturdays and bring over what I did during the week from the other Angular repo. The features that I worked on this week are, multiple-select filters and custom filters, which you can see on the [Angular Wiki](https://github.com/ghiscoding/Angular-Slickgrid/wiki/Select-Filter#ui-sample-1). Another feature that got half started at work is Export to File (csv/text) coming soon. We are almost feature finish at work with the grid for our app needs, so it will go down soon on the feature side of it.

Side note 3
I also contribute directly to the SlickGrid repo, for example the Grid Menu (hamburger menu) was my code pushed to SlickGrid repo. And another big feature that we worked on this week, with another great collaborator, is Row Detail panel which you can see [here](https://github.com/6pac/SlickGrid/issues/128#issuecomment-366310589), again it's pure html template I'd like to get that working in Aurelia as well in the future.

**Comment by jmzagorski** [comment]
That's great to know, thank you for the explanation

As for me, I am coming back to slickgrid after a few years away from it. I started in 2014 on a project that had plain old JavaScript and needed to rendered thousands of rows quickly, so it worked perfectly.

I push Aurelia at my work as well since it stays close to web standards and is simple/clean. I have been using it for a little over a year and cannot complain. I set out to integrate slickgrid-es6 with aurelia (little less than a year ago), but i didn't have the time to code a project and plugin so I used kendoui-grid with Aurelia since we had a license (what a headache!). So when I saw your project I was very happy.

My current project has an administration section that is in need of a good grid so I will be happy to contribute as I use your plugin. I will add a commit for  the wiki to better explain myself over the next couple of days. 

I can include this in the wiki: [dispatchEvent](https://developer.mozilla.org/en-US/docs/Web/API/EventTarget/dispatchEvent) is a plain old JavaScript API that any code can listen to with [addEventListener]( https://developer.mozilla.org/en-US/docs/Web/API/EventTarget/addEventListener). However, with Aurelia we don't need to use `addEventListener` because Aurelia gives us the `delegate` binding in the view to call our view model methods. That way, we don't need to have a dependency on the `EventAggregator` in our view models to handle events. By iterating over all the `on` properties in the grid and data view you can add any slickgrid event in your view such as:

```
<template>
  <aurelia-slickgrid 
    grid-id="members-setup" 
    column-definitions.bind="columns" 
    grid-options.bind="gridOptions" 
    dataset.one-way="memberList"
    sg-on-add-new-row.delegate="methodInViewModel($event.detail.args.item)"
    grid-height="400" 
    grid-width="800">
  </aurelia-slickgrid>
</template>

```


Finally, I did see that you contribute to to the SlickGrid repo and saw that pull request you made because I will need something like that for my nested arrays. Can't wait for that to merge!

**Comment by ghiscoding** [comment]
Oh wow your history with SlickGrid is so similar to mine... I got away from SlickGrid for a year to go with UI-Grid (AngularJS) mostly because of the fact that SlickGrid ~~wasn't supporting~~, or so I thought at the time, backend async services and pagination (which UI-Grid supported). But now that I came back with it and spent a bit more time investigating, I found how to deal with async data. 

SlickGrid is still by far the best datagrid I ever used and tried. Funny enough, my first version of Aurelia-Slickgrid 0.x (before my Angular repo actually) was using Slickgrid-ES6 but I found there was a few things that weren't working with it (mainly all SlickGrid plugins weren't working) and so I re-released a new version 1.x going back to 6pac fork which is the best thing I've done. It's repo is much more active and I also contribute to it myself 6pac with my PRs as well, so it's a great community. 

Thanks for the quick sample, I now understand why the kebab casing when I see your view. It's cool, you don't even need the SlickGrid object anymore. This make things quite interesting with a different approach. 

As for the PR, I expect it to be merged in the next couple days. I could actually merge it myself, 6pac (Ben) made me a contributor and I have merge permission, but I prefer that he has a quick review, even though it's a standalone plugin. He also told me that he was waiting for this PR to releases a few other commits and a new version number. There's a few commits in the queue and I also did 2 other small PRs to have the possibility to hide the 2 last checkbox in Column Picker/Grid Menu, I never use these checkbox and I never understood what "Synchronous Resize" does anyway lol

**Comment by jmzagorski** [comment]
I am using a simple JSON dataset because my app has a simple RESTFUL api using redux-saga, but since I have a dashboard page I am sure I may need to use GraphQL or something similar later one (I am using .Net core as well).

I plan on working on the wiki today and possibly submitting another pull request for a simple feature.

**Comment by jmzagorski** [comment]
I am a noob when it comes to updating someone else's wiki (I thought I could make the changes in my repo and include just my wiki change in this pull request). From what I found, I need to clone your repo wiki and push the change directly to your `master` wiki branch, but I am guessing I cannot push directly to your wiki since I am not a contributor (but I have not tried this yet) and, if it did work, you would have no way to review the changed documentation.

How would you like to proceed with that change? Below are my changes to https://github.com/ghiscoding/aurelia-slickgrid/wiki/Grid-&-DataView-Events (also, I was not sure what `EventEmitter` was referring to in the wiki):

SlickGrid has nice amount of [Grid Events](https://github.com/6pac/SlickGrid/wiki/Grid-Events) or [DataView Events](https://github.com/6pac/SlickGrid/wiki/Dataview-Events) which you can use by simply hooking a `subscribe` to them (the `subscribe` is a custom `SlickGrid Event` and is **NOT** an `RxJS Observable` type but is very similar). There are two ways to get access to all these events:

1. You will have to bind to the `Grid` and the `DataView` objects which are exposed in `Aurelia-Slickgrid` with `EventEmitter` (`Aurelia-Slickgrid` uses `emit` after the `Grid` and `DataView` becomes ready). Once these are called, it basically mean that the `Grid` and `DataView` are ready and we can `subscribe` to any of the [SlickGrid Events](https://github.com/6pac/SlickGrid/wiki/Grid-Events). 

2. Add event handlers in your view with Aurelia's `delegate` binding. This library bubbles all events for the `Grid` and `DataView` by converting the camelcase methods to kebab case (`onMouseEnter` will be `sg-on-mouse-enter`. "sg" (SlickGrid) is just an identifier to indicate the event is dispatched from slickgrid). We also expose events emitted from the `AureliaSlickGridCustomElement` (see [Event Aggregator](#event-aggregator)). Slickgrid's EventData and Args parameters will be passed via $event.detail.eventData and $event.detail.args. For example:

```html
<template>
  <aurelia-slickgrid 
    grid-id="gridId" 
    column-definitions.bind="columnDefs" 
    grid-options.bind="gridOptions" 
    dataset.one-way="myDataset"
    grid-height="400" 
    grid-width="800"
    sg-on-click.delegate="handleClick($event.detail.eventData, $event.detail.args)"
    sg-on-mouse-enter.delegate="handleMouse($event.detail.eventData, $event.detail.args)">
  </aurelia-slickgrid>
</template>
```

**Comment by jmzagorski** [comment]
To answer you first question about the wiki: Would this be similar https://github.com/ghiscoding/aurelia-slickgrid/pull/6/commits/0b4d05750c42e90e8fb88ea1a2bb9007f70d6e07, which i reverted? But instead of including all your wiki pages, just include the page I need to change?

About your second question: I meant to change that to `bind` instead of `one-way`. I use redux with aurelia so most of my bindings are `one-way`. With slickgrid I add the `editCommandHandler` grid option so slickgrid does not edit my data and I can call my redux actions => update my api => change my local data => which then fires your `dataChanged` event in the `AureliaSlickgridCustomElement`

**Comment by ghiscoding** [comment]
Yes for the wiki, I'm trying to make it simple for you but also have history on my side. Whatever is easier for you, I will accept it in the PR.

I've never tried React neither Redux, though I'm happy to hear that my lib works well with it :)

**Comment by jmzagorski** [comment]
Funny thing is I've never used React either (i started with Angular 1.x and moved to Aurelia). I just liked the philosophy of redux.

Anyway, all my commits should be in for this request. I have two more small pull requests to create, but I will wait for this one to merge first.

**Comment by ghiscoding** [comment]
Thanks I'll take a look at it in couple of hours. 
I also have a branch that I'm trying to finish up (possibly tonight) with Multiple-Select Filter and Custom Filter. It's probably better if you wait for that branch, soon to be PR, to be merged as well before starting other changes. 

The redux philosophy, isn't it related to their State Management which they announced recently to go on the 2018 roadmap?

**Comment by jmzagorski** [comment]
Yes, I am super excited about that! I took a look at https://github.com/zewa666/aurelia-store to get an idea of what others are doing. If I ever have time I might create a aurelia redux plugin since all the logic is already in my application and it would be nice to refactor it into a library. However, if i like RxJs and what aurelia-store will do when it is stable, I might just adopt that too.

**Comment by ghiscoding** [comment]
We are using Angular 5 at work (again not my decision) and Angular is all based around RxJS, even the `http` result is returning an RxJS Observable. Within the Angular-Slickgrid version (not the Aurelia one though), I take that `http` result and convert it into a Promise to deal with it, I didn't put that in my Aurelia version because we can assume that Aurelia always return a Promise from an `http` result. 

RxJS is nice for some stuff, but it's different compare to a Promise for a few reasons
- Observable can be subscribed multiple times, while Promise only happen once and is dead after the `.then` is finished. 
- If your Observable is meant to execute only once (like Angular `http` result, which is a special case), then you can convert it to a Promise with `toPromise()`

However, unless I want to subscribe multiple times , I still prefer Promises, why? 
- because I can use the new `async/await` syntax
- because RxJS Observable are written with callback in mind and try/catch are also written the old Promise way. 
  - seriously they could improve on that end, I feel like going backward and write it like the first iteration of Promises lol

I read somewhere that we don't actually need RxJS in Aurelia since we have the `Event Aggregator` and it basically does roughly the same thing. I know it's not related to redux neither State Management, but since you talked about RxJS, I felt like writing on the subject :P

Seriously, I wish that I could use Aurelia full time instead of just personal projects. But at least I got a few plugins/libs and it helps me and people in the community.

**Comment by ghiscoding** [comment]
Awesome, I tested it on my side and seems to be all good. 

Questions and comments
- do you think we should change the `Event Aggregators` to be all `Element Dispatch`? 
  - I never used them, so I'd like to have your comments on that subject
- for future PR, would it be possible to exclude the `dist` folder from the PR itself, it kinda clutters the PR
  - though please run the Build, to make sure that there are no Build errors
  - if you can't or don't know how to remove the `dist` folder, no big deal, I will still accept your PR :)

On my side
- I finally got all code and the Build working for the Multiple-Select Filter and Custom Filter
- I will also create a PR and merge your code, I expect some small conflicts since we both touched `aurelia-slickgrid.ts`. 
- Expect a new version `1.5.0` that will include your PR (thanks) and mine (sweet) by the end of the week. 

Stay tuned

**Comment by jmzagorski** [comment]
Here are some answers to your questions:

- do you think we should change the Event Aggregators to be all Element Dispatch?
Yes, but would that be part of a 2.0 release since it would break your custom elements API?

- for future PR, would it be possible to exclude the dist folder from the PR itself, it kinda clutters the PR
Yes, absolutely.

Great job with the 1.5 release! I have a few questions/comments as well:

1. Could you help me better understand your /doc folder? I was looking for a changelog.md file that describes the changes with your versions and I could not find that file, but I saw it referenced in a script in `package.json`? If you do not have one, I would be more than happy to help. Convention-changelog has replaced their cli with https://github.com/conventional-changelog/standard-version and I have a lot of success with it. Doing this would require changing the style of commit messages to the angular convention that a lot of libraries use, including aurelia.
2. I have a few features requests from my users that I am working on. As I find any new features/fixes, do you want me to 1. create pull requests and you can review the changes at that moment or 2. add them to your project page so you can see what I have in my queue in case you need to revise/reject any of the features/fixes?
3. Unit tests: Where do you stand on unit tests for future development and for code that exists already?

**Comment by ghiscoding** [comment]
Thanks, here's some of my answers. 
> Yes, but would that be part of a 2.0 release since it would break your custom elements API?

- I don't necessarily block myself from deprecating things, I add `console.warn` with a deprecating message and I leave the code in place (including the deprecated code) until further versions. For example, I rewrote the Backend Service API, but the previous code is still in there with a warning, I'll delete previous code in a month or 2.
- I actually thought about the difference between the `Element Delegate Dispatch` and the `Event Aggregator`, they actually serve different purpose and I think that I will leave them both there. The `Event Aggregator` is good when you want to send an event globally, which the `dispatch` won't be able to do since it's attached only that element.

Your questions
1. I'm not following anything in particular, if you want to see the changes, I write them all in the release itself, which is why I told you to take a look at the [version 1.5.0](https://github.com/ghiscoding/aurelia-slickgrid/releases/tag/v1.5.1), I explain the changes with some links to the wiki docs.
  - The convention changelog might already be in place since I took the scripts from an Aurelia lib, I just never ran them. If you want to take a look at it, sure go ahead
2. You can start by opening an issue and we can start a discussion in that issue, that would avoid for both of us working on same possible features. Once all set and you start coding, you could then reference the PR against the issue.
3. Unit tests, I have none since this project is all but done on personal time. I would love to have some but I prefer to push features out. I definitely think that the lib should have tests, I just don't know when I'll reach that portion. If you want to start some, please, please go ahead.

**Comment by jmzagorski** [comment]
Great thanks! I have two very small changes that I will just submit via pull requests since I already have them done and branched (hopefully that is okay, if not I can open an issue), but I'll start to open issues with future features/fixes.

**Comment by ghiscoding** [comment]
It should be ok, the next feature that I'm working on at work is Export to file (csv/text) and that won't go in Aurelia until next weekend which is usually when I do Aurelia stuff. If your thing are non-related, then yes go ahead. Thanks

**Comment by ghiscoding** [comment]
@jmzagorski 
Hey I just fixed a missed `dispose()` of the `Event Aggregator` that I have in Aurelia-Slickgrid (found the issue in my Angular version actually) and that got me wondered in your PR you also have a `subscribe` at these lines [here](https://github.com/ghiscoding/aurelia-slickgrid/blob/master/aurelia-slickgrid/src/aurelia-slickgrid/aurelia-slickgrid.ts#L268) and [here](https://github.com/ghiscoding/aurelia-slickgrid/blob/master/aurelia-slickgrid/src/aurelia-slickgrid/aurelia-slickgrid.ts#L282) but you also didn't disposed it. Is that something you missed or something that isn't necessary in the way you coded it?

**Comment by jmzagorski** [comment]
@ghiscoding 
After reviewing the slickgrid code, I made a bad assumption that `grid.destroy()` cleans up events. I will send in a fix for this.

**Comment by ghiscoding** [comment]
@jmzagorski 
I think we can do an `unsubscribeAll()` if we subscribe to all events like [this](https://github.com/6pac/SlickGrid/blob/master/plugins/slick.headerbuttons.js#L78) 

What you said also makes me think that the ones I have for `onCellChange` and `onClick` probably have the same problems... yes they do, I'm missing a [destroy](https://github.com/ghiscoding/aurelia-slickgrid/blob/master/aurelia-slickgrid/src/aurelia-slickgrid/services/gridEvent.service.ts#L7) as well.

**Comment by jmzagorski** [comment]
You read my mind about `unsubscribeAll`. Already had the [pull request](https://github.com/ghiscoding/aurelia-slickgrid/pull/12) in process.

**Comment by ghiscoding** [comment]
@jmzagorski 
The `onCellChange` and `onClick` are subscribed in the gridEvent.service` which is missing a `destroy()`. Technically if you unsubscribe all SlickGrid, I don't even need to do that but it's probably better anyway to make it more consistent. 

BTW, do Services also use  `detached` in Aurelia or should I stick with `destroy` method? I have `destroy` in most Services but if `detached` is the "correct" way of doing it in Aurelia, I can rename them all. I guess I will still have to call them manually (all Services destroy/detached) in the `aurelia-slickgrid` `detached`.

**Comment by jmzagorski** [comment]
In Aurelia, since there is a difference between a view-model and custom element, `detached` in only applicable on a custom element.

I think we need a `destroy` or `dispose` in the `GridEventService` to clean up those subsciptions. Then event handler in the `AureliaSlickgridCustomElement` only cleans up the events explicitly set through the `Slick.EventHandler`, which means the events in the `GridEventService` could still be hanging around in memory. 

A `dispose` method is more natural for services to call to clean up resources (similar to calling `Dispose` in .NET)

**Pull request merged**
