### PR TITLE
 fix(filterFactory): create a new filter instance on every call 

### PR DESCRIPTION
**Pull request by jmzagorski**
This pull request fixes singleton filters in the `FilterFactory` because `All.of` was used in the `FilterFactory` constructor. It should close https://github.com/ghiscoding/aurelia-slickgrid/issues/20. 

**Changes**
1. Filter registration was changed to `registerTransient` instead of `registerSingleton`
2. The `FilterFactory` uses the Aurelia's `container.getAll` method to find the correct filter every time `FilterFactory.createFilter` is called

I'd like to mention one of several other alternatives. I could use the `filterType` value as the registration key. That would change the developer registration to `aurelia.container.registerTransient(FilterType.input, Filter.inputFilter)` instead of `aurelia.container.registerTransient(FILTER_PLUGIN_NAME, Filter.inputType). `

**Alternative Benefits**
1. Do not need a `FILTER_GRID_PLUGIN` constant 
2. Do not need to call `container.getAll` to iterate over all the filters. We can call `container.get(filterType)` instead.

**Alternative Cons**
1. Registration key could have conflicts unless we created a `FILTER_GRID_PLUGIN_PREFIX` constant so the registration would look like `aurelia.container.registerTransient(FILTER_GRID_PLUGIN_PREFIX + FilterType.input, Filter.inputFilter)` and we would get the filter by `container.get(FILTER_GRID_PLUGIN_PREFIX + filterType)`.
2. The filters would not be registered together.

However, I went with the current solution since it was similar to our prior API and it follows the convention for plugin registration. Also, I could have implemented a caching technique with `container.getAll`, but there didn't seem to be noticeable overhead by calling `container.getAll` every time to find the correct filter  

- [ ] After this pull request is approved I will update the CustomFilter wiki from `registerSingleton` to `registerTransient`
- [ ] Add dependency injection with CustomFilter example

### CODE REVIEW

**Comment by ghiscoding** [comment]
Looks good at first glance, I will review it more tonight after work. Though I have some quick notes
- I read somewhere that TypeScript now discouraged adding the `types` in javadoc, so `@param {string} inputStr` should just be `@param input string`
  - the reason is simple, we have intellisense with TypeScript so there's no need to add it again to the jsdoc
  - there is apparently a flag also in TSConfig that if enabled will fail on these `{type}` in curly braces
- IE and Edge are the ones that are more impacted on performance side, for example the Example 4, if I drag & drop a column position, it takes 2sec in Edge to re-render the grid, but in Chrome/Firefox it's instant. I'm really surprised that Edge is still impacted by performance in SlickGrid, I usually see these perf hit when dragging a column or grouping thousand of rows.

**Comment by jmzagorski** [comment]
So is this performance impact you see because of the change? I thought once the grid is rendered that Factory does not need to be called again. Or are you saying "in gerernal" those two browsers perform slower?

**Comment by ghiscoding** [comment]
I wouldn't go with caching, I think it's overkill and pron to caching issues. 

No the perf hit was always there in IE, I'm really surprised it's still there in Edge but anyhow it's still present. 

To give a bit more explanation on the Filters, I actually found a bug today in Angular/Aurelia, when you drag a column to another position, it will re-render the entire grid **and** the element filter. The bug I just fixed in Angular for now, is that the filter element (try on the multiple-select) loses his selected values. I'm not sure why it's slow in Edge, in theory SlickGrid only create DOM node for what is displayed on screen with a buffer of about 5 nodes on top/bottom, which is why when you scroll very far it's white at the beginning (that's the re-creating of DOM nodes that kicks in). I have a feeling that perf hit is because Edge/IE suck with arrays (like sort, reposition, filter, ...)

**Comment by ghiscoding** [comment]
Reviewing your PR and the comment you posted in the issue
> What if we added a defaultFilterType to the SlickgridConfig that the user can override with their own configuration during the startup of the app when we pass the config object to them in main.ts here https://github.com/ghiscoding/aurelia-slickgrid/blob/master/aurelia-slickgrid/src/aurelia-slickgrid/index.ts#L66

I tested that part and I didn't know you could just use 
`import { SlickgridConfig } from '../slickgrid-config';`

That's cool, however, if I change my `main.ts` with
`config.options.defaultFilterType = FilterType.select;`

I was expecting that it might change all the input filters to a select but that didn't happen. Am I suppose to see something change or not? I did put a breakpoint to the Factory constructor and it does get the option of `FilterType.select`. It doesn't matter much for the fix, but I'm just curious to know what adding that option in the global config might do

**Comment by jmzagorski** [comment]
ah good catch, I forgot to register your instance with the container. Add this after you `new` the `SlickgridOptions`:
```
  aurelia.container.registerInstance(SlickgridConfig, config);
```
if that works as you expected let me know and i can add that commit

**Comment by ghiscoding** [comment]
Sorry, I'm not sure where you want me to add that line. Is that in the Factory or in the Config? 
BTW, it's not merged yet so any commit will follow

**Comment by jmzagorski** [comment]
add it after https://github.com/ghiscoding/aurelia-slickgrid/blob/master/aurelia-slickgrid/src/aurelia-slickgrid/index.ts#L63. 

I'll be able to commit the change a little later tonight.

**Comment by ghiscoding** [comment]
Ok I did that but still don't see any visual or behavior difference in the UI. The input filters remains input and they still work as an input.

**Comment by ghiscoding** [comment]
We can do a separate PR if that helps. As long as we have the main fix resolved.

**Comment by jmzagorski** [comment]
The changes in now should resolve the issue. To get that `defaultFilterType` to work I need to remove this line https://github.com/ghiscoding/aurelia-slickgrid/blob/master/aurelia-slickgrid/src/aurelia-slickgrid/services/filter.service.ts#L316

I did not see that before. Do you have any problem with that?

**Comment by ghiscoding** [comment]
hmm ok, I guess you will pass the filterType in a different way to the switch/case?

**Comment by jmzagorski** [comment]
Yeah sorry I didn't mean delete, i meant change it. Your filter service needs to know the filterType so that line would change to 

```
const filterType = (columnDef.filter && columnDef.filter.type) ? columnDef.filter.type : this._gridOptions.defaultFilterType;
```

which means your filter service will never pass an unknown or null filter type to `FilterFactory`, but the `FilterFactory` does not know that so it is a good safe guard in the `FilterFactory` to still have the `defaultFilterType`.

I did find one odd thing though. `SelectFilter` does not have a `filterType` property when I set a break point in the filter factory? I set the defaultFilterType. Do you see that too?

**Comment by ghiscoding** [comment]
Right I just found the problem, my VSCode was also showing it in different color, the same color as a type... oh yeah you made it a type instead of an assignment :P  change the `:` to `=`

**Comment by jmzagorski** [comment]
okay, new commit is in and that is it for me tonight. Hopefully these fix the problem. I'll catch up with everything tomorrow.

**Comment by ghiscoding** [comment]
@jmzagorski 
Hey I just wanted to make sure, you're all done with the PR right? I ask bcoz you wrote 
> I'll catch up with everything tomorrow.

So just wanted to make sure before I merge. Thanks

**Comment by jmzagorski** [comment]
yes, sorry. I meant I will catch up on the WIKI change and changes in my other future PRs

**Comment by ghiscoding** [comment]
Ok thanks, I'll push a new version tomorrow or Monday. 
You can update the wiki on Monday, I'll put a note in the Project page

**Comment by jmzagorski** [comment]
@ghiscoding 

Updated the wik page https://github.com/ghiscoding/aurelia-slickgrid/wiki/Custom-Filter. I will try to make my revision comments short and to the point https://github.com/ghiscoding/aurelia-slickgrid/wiki/Custom-Filter/_history

```diff
- Register your filter with the aurelia container 
+ Register your filter with the `registerTransient` method on the aurelia container 
```

```diff
- aurelia.container.registerSingleton(FILTER_PLUGIN_NAME, MyCustomFilter);
+ aurelia.container.registerTransient(FILTER_PLUGIN_NAME, MyCustomFilter);
```

Added a new section before **Default Search Term(s)**

### Default Filter Type
By default, the library uses the [inputFilter](https://github.com/ghiscoding/aurelia-slickgrid/blob/master/aurelia-slickgrid/src/aurelia-slickgrid/filters/inputFilter.ts) when none is specified. However, you can override this value with any filter you like during the startup/configuration of your Aurelia application:

**main.ts**
```typescript
  aurelia.use.feature(PLATFORM.moduleName('aurelia-slickgrid/index'), config => {
    // change any of the default global options
    config.options.defaultFilterType = 'myCustomFilter' // or you can use another library Filter
});
```

**Pull request merged**
